export const QUESTION_CREATE_REQUEST = 'QUESTION_CREATE_REQUEST'
export const QUESTION_CREATE_SUCCESS = 'QUESTION_CREATE_SUCCESS'
export const QUESTION_CREATE_FAIL = 'QUESTION_CREATE_FAIL'

export const SET_CATEGORY_REQUEST = 'SET_CATEGORY_REQUEST'
export const SET_CATEGORY_SUCCESS = 'SET_CATEGORY_SUCCESS'
export const SET_CATEGORY_FAIL = 'SET_CATEGORY_FAIL'

export const SET_ANSWER_REQUEST = 'SET_ANSWER_REQUEST'
export const SET_ANSWER_SUCCESS = 'SET_ANSWER_SUCCESS'
export const SET_ANSWER_FAIL = 'SET_ANSWER_FAIL'
